-- Create a table for public profiles
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  
  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- Projects Table
create table projects (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  theme text not null,
  status text check (status in ('ideation', 'scripting', 'assets', 'production', 'completed')) default 'ideation'
);

alter table projects enable row level security;

create policy "Users can view own projects" on projects
  for select using ((select auth.uid()) = user_id);

create policy "Users can insert own projects" on projects
  for insert with check ((select auth.uid()) = user_id);

create policy "Users can update own projects" on projects
  for update using ((select auth.uid()) = user_id);

create policy "Users can delete own projects" on projects
  for delete using ((select auth.uid()) = user_id);

-- Ideas Table (Generated by Gemini)
create table ideas (
  id uuid default gen_random_uuid() primary key,
  project_id uuid references projects on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  metrics jsonb, -- { engagement_score: 95, cost: 'medium', ... }
  selected boolean default false
);

alter table ideas enable row level security;

create policy "Users can view ideas for own projects" on ideas
  for select using (
    exists ( select 1 from projects where id = ideas.project_id and user_id = (select auth.uid()) )
  );

create policy "Users can insert ideas for own projects" on ideas
  for insert with check (
    exists ( select 1 from projects where id = ideas.project_id and user_id = (select auth.uid()) )
  );

-- Scripts Table
create table scripts (
  id uuid default gen_random_uuid() primary key,
  project_id uuid references projects on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  content jsonb not null, -- Structured script data (scenes, dialogs)
  version int default 1
);

alter table scripts enable row level security;

create policy "Users can view scripts for own projects" on scripts
  for select using (
    exists ( select 1 from projects where id = scripts.project_id and user_id = (select auth.uid()) )
  );

-- Assets Table (Images, Videos)
create table assets (
  id uuid default gen_random_uuid() primary key,
  project_id uuid references projects on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  type text check (type in ('image', 'video', 'audio', 'character_sheet')) not null,
  url text not null,
  prompt text,
  metadata jsonb -- Extra info like scene_id, character_id
);

alter table assets enable row level security;

create policy "Users can view assets for own projects" on assets
  for select using (
    exists ( select 1 from projects where id = assets.project_id and user_id = (select auth.uid()) )
  );

-- Function to handle new user signup
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
